### ISSUE TITLE
automatically handle "autofocus"?

### ISSUE THREAD

**Issue by leeoniya** [domvm/domvm#168]
currently it's easy to accomplish this via a `didMount` or `didInsert` hook but would be useful to have this handled transparently. the question is "how?".

it's too expensive to test every node's type & attrs for "autofocus" during node creation or preProc. probably it would be added to `vm.mount()` and `vm.attach()`, but would require traversing the entire vtree and test all nodes for the presence of "autofocus". this is probably the least perf-affecting route, but i'm not sure it's even worth the extra code or effort.

**Comment by lawrence-dol** [comment]
I've done this by searching on the next event loop after rendering, which hasn't had a visible effect on performance. But it happens to work, I think, because rendering never happens when any other elements are focused (otherwise it would steal focus from them).

    genU.defer(0,function() {
        let elm=document.find("?[autofocus]");
        if(elm) {
            appU.scrollIntoView(elm,"DIV","data-kiv",true);
            elm.focus();
            }
        });

I think one problem would be knowing that the input with autofocus was actually just mounted, as opposed to happens to (still) exist in the tree. Maybe this should only happen on initial rendering, in which case `didMount` on the document root would work.

I don't know how well it will play with multiple components though, each of which specify an autofocus element.

**Comment by lawrence-dol** [comment]
In my latest app I solved this by tagging all inputs that are eligible for autofocus and then using a hook to focus on the first one (this let me omit other focusable navigation elements), while falling back to defaults.

````
function focusDefaultAtr(key) {
    function focusDefaultFnc(vm) {
        let elm=document.find("?#ruru-booking .focus-default") || document.find("?.nav-button.action-next") || document.find("#ruru-booking") || document.body;
        genU.deferEL(function() { elm.focus() });
        }

    return {
        _key                            : key,
        _hooks: {
            didInsert                   : focusDefaultFnc,
            didReinsert                 : focusDefaultFnc,
            }
        };
    }
````

**Comment by lawrence-dol** [comment]
Personally, after reflecting on the app where I did this, I think that the concept I implemented is vastly superior than trying to conditionally the one tag that, in this data context, should be automatically focused. I suggest this issue be closed. Autofocus as supplied by HTML is clumsy.

**Comment by leeoniya** [comment]
:+1:
