### ISSUE TITLE
Bug: parsing negative attributes in tag definition

### ISSUE THREAD

**Issue by jlgrall** [domvm/domvm#208]
The code:
```javascript
el("input[type=number][min=-1]");
```
Generates:
```html
<input type="number"></input>
```
Instead of:
```html
<input type="number" min="-1"></input>
```
Example: https://domvm.github.io/domvm/demos/playground/#mobx

**Comment by leeoniya** [comment]
hmm, good catch. so the regex right now is this:

```js
/\[(\w+)(?:=(\w+))?\]/g
```

the question is, how loose to we want it? do we handle/avoid/absorb quoted values?

**Comment by leeoniya** [comment]
changes are up!

**Comment by jlgrall** [comment]
> how loose to we want it?

I would say to keep it straightforward to not slow down parsing and vdom generation. So no quotes.

I would add a minus sign to the attribute name to allow for "data-*" attributes, and a `:` for namespaced attributes (in SVG for example).

I looked at different possible attributes at: https://developer.mozilla.org/en/docs/Web/HTML/Element/Input  
I would also add to your regexp:
- the _space_ for class, time and date values, …
- `:` for input that accept time and hours values
- `;`
- `#` for input of type color
- `%` for percentages values

And optionally:
- `(` and `)` for phone numbers
- `/` for urls and links
-  `@` for emails
- `~` for urls
- `'` often used in english sentences
- `&` 

But I actually don't see why you couldn't use a simpler regexp  like:
```javascript
/\[([^=\]]+)(?:=([^\]]+))?\]/g
```
Then, what would happen with code like this: `el("div[<>'\\  =]");` ? If it still triggers an error, then I think you can use the simpler regexp.

**Comment by leeoniya** [comment]
> I would add a minus sign to the attribute name to allow for "data-*" attributes

good call.

> and a `:` for namespaced attributes (in SVG for example).

namespaced attrs are not supported anymore [1]. they were never fully supported anyways because testing for namespace presence requires to test all attr names for `:`, split that, then use a somewhat different creation and mutation path. on top of that you might need to have the xmlns URIs stored in the lib. `xlink:href` is the somewhat commonly encountered variant and a holdout on iOS and Safari [2].

if we can make it work without taking a big perf hit on all attrs, then i'm okay with that. you can see from [1] that it was only special-cased for `xlink:href` on svg nodes.

> But I actually don't see why you couldn't use a simpler regexp like:
>
> ```js
> /\[([^=\]]+)(?:=([^\]]+))?\]/g
> ```

i suppose this will have to be it, given the large list of cases.

[1] https://github.com/domvm/domvm/search?q=xlink&unscoped_q=xlink&type=Commits
[2] https://css-tricks.com/on-xlinkhref-being-deprecated-in-svg/

**Comment by jlgrall** [comment]
The advantage with the simpler regexp is that it doesn't skip attributes that contain unsupported characters. It took me a few days to notice that the `[min=-1]` was not rendered, because I forgot that I wrote it. It is always better to not ignore errors.

I would also accept a `=` without a value. After all, HTML accepts empty attributes, so it is less surprising to accept it too.

> i would add `\s` to the attr name exclusions

If you accept: `el("div", {"at tr": "val"})`, I think you can also accept `el("div[at tr=val]")`. At least this way it has a chance to trigger an error on the client instead of being completely ignored.

Which would give us:
```javascript
/\[([^=\]]+)(?:=([^\]]+)?)?\]/g
```

**Comment by leeoniya** [comment]
both the "uniformity" and "error on the client" arguments are strong.

**Comment by jlgrall** [comment]
Looks good.
