### ISSUE TITLE
Passing data around templates and sub-templates

### ISSUE THREAD

**Issue by Veid** [domvm/domvm#211]
Hey everyone,

This might be more of a general architecture question / javascript question, but it's related to domvm -- so I thought I might ask here to see how others approach this problem. Or what @leeoniya thinks.

I've been creating some more complex UIs recently, with view / template trees broken up into several different files that relate to that portion of the interface. How do you deal with passing around data god objects or portions of them? To try and make this more concrete, here's an example:

Suppose we're working with a pretty large UI. To start out, it's a monolithic view -- but we try to break up some of the complexity by dividing it into sub-templates and those sub-templates have sub-templates, etc. In this example, we have files like `./view.js`, `./templates/template1.js`, `./templates/template2.js`, `./templates/subfolder/sub2.js`, ..., etc.

So we might have the entry, doing a preinit-view-wrapping model as in https://github.com/domvm/domvm/issues/90#issuecomment-231502588:

```javascript
// Maybe this is the entry ./main.js
var View = require('./view');

function ViewModel(data) {
    this.vm = domvm.view(View, data);
}
var v = new ViewModel({
    stuff : ...,
    ...
});
```

```javascript
// Inside of ./view.js
var type1Level1Tpl = require('./templates/type1level1');
var type2Level1Tpl = require('./templates/type2level1');
var type3Level1Tpl = require('./templates/type3level1');

function MainView(vm, data) {
    return function() {
        return el('#main', [
            type1Level1Tpl(data),
            type2Level1Tpl(data),
            type3Level1Tpl(data),
        ]);
    }
}
```

```javascript
// Inside of ./templates/type1level1
function subSubTpl1() {
    // This function might want something from data, maybe data.pieceOfData1
    // or data.part1.piece1.sub1, etc.
    return el('.subsub1', 'Sub Sub 1');
}

function subTpl1() {
    return el('.sub1', 'Sub 1');
}

function subTpl2() {
    return el('.sub2', 'Sub 2');
}

function subTpl3() {
    return el('.sub3', [
        subSubTpl1()
    ]);
}

function type1Level1Tpl(data) {
    return el('.l1t1', [
        subTpl1(),
        subTpl2(),
        subTpl3()
    ])
}
```

And so on with `type2Level1` and `type3Level1` with their own nesting, possibly requiring other templates contained in their own files. How do others pass around data in this situation?

Should one pass around the `data` object as a parameter to every template function? Like this:

```javascript
function type1Level1Tpl(data) {
    return el('.l1t1', [
        subTpl1(data),
        subTpl2(data),
        subTpl3(data)
    ])
}
```

Or, possibly, try to only pass what's needed?

```javascript
function type1Level1Tpl(data) {
    return el('.l1t1', [
        subTpl1(data.somePortion),
        subTpl2(data.anotherPortation, data.somePortion),
        subTpl3(data)
    ])
}
```

In the case of `subTpl1(data.somePortion)`, what if it turns out that another sub-template within this template requires some other section of `data`? Would you modify the function signature of the entire chain of functions to include the new piece of data?

```javascript
function subTpl1(somePortion) {
    return el('.sub1', [
        ss1(somePortion, 'black', 10)
    ]);
}

function ss1(somePortion, color, size) {
    return el('.ss1', [
        return piece1(color, size * 2)
    ]);
}

function piece1(color, size) {
    // Data object not available here, should we rewrite this
    // function to have a third parameter? And rewrite the
    // above functions to take +1 parameters?
    return el('.p1', '' + color + size + data.anotherProperty)
}
```

This seems cumbersome? If we've broken up some portion of the UI into a file, there's generally a root template within that file. Something I've toyed with:

```javascript
var somePortion;
var anotherPortion;

function t1(){console.log(somePortion)}
function t2(){console.log(anotherPortion)}

function rootTpl(data) {
    somePortion = data.somePortion;
    anotherPortion = data.anotherPortion;

    return el('.root', [
        t1(),
        t2()
    ]);
}
```

So this makes `somePortion` and `anotherPortion` globals within the file. This can be problematic if, for example, you need multiple instances of the UI. But it does cut down on the, possibly, excessive data passing / large function signatures / needing to modify large chains of function signatures for new sub-templates that need another portion of data.

I hope what I've written is mostly understandable. Look forward to hearing what others might have to say about this.

Thanks!

**Comment by leeoniya** [comment]
seems like a case of prop-drilling blues?

https://medium.com/@MCapoz/passing-data-in-react-with-prop-drilling-904aeb3cb5e

react introduced the context API to deal with this:

https://itnext.io/compound-components-with-react-v16-3-6679c752bd56

domvm allows something similar to this:

https://github.com/domvm/domvm#createcontext

personally, i try not to micro-segement the state in my apps for the sake of passing down "only what's necessary" since it can quickly become a nuisance with every change/refactor you need to make. i usually use some combo of `vnode.pull()` from within `.render()` or pass down a global state object.

**Comment by lawrence-dol** [comment]
I would like to write a deep-dive on what I've done, but time doesn't permit the detailed study of the code which would make that accurate. So instead, here's my high level approach.

First I write all of my code inside modular units which are essentially a one-function-file which exposes a constructor for the module (module in the comp-sci sense, not JS). This gives me "use strict" for all code, private state and a constrained context in which to reason about the code. I do not use OO objects and thus have no use for `this`. The constructor returns a JS object of the module's public API functions. IOW, the "old fashioned" JS module design.

Now, there's two kinds of "state": UI (or "view") state, and program state. I differentiate between the two and model the latter using a mix of modules for the values which control the program's operation, and plain JS objects for volume data (typically received from the host) which is rendered for, and updated by the user. This keeps the really large datasets as light as possible. I then have code modules which know how to manipulate any given dataset. Oddly, in JS, I've eschewed the OO of Java which I had learned to love and returned to a mix of functional and procedural code operating on externally defined data types.

So then my views are (comp-sci) modules which happen to expose the needed rendering functions in their API. These modules are injected with the necessary means to get the data to be rendered (either by direct injection, or being supplied with an abstraction that can obtain the data on demand).

Thus, my handing of state is almost entirely orthogonal to the generation the DOMVM views. I think I use the DOMVM data object for the aforementioned view state, because, well why not?

**Comment by Veid** [comment]
@leeoniya -- interesting, I'm going to dig into what else I can find on approaches for "prop-drilling blues", thanks! It seems domvm's `createContext` is possibly only useful when dealing with views and sub views? For example:

```javascript
// main.js
const el = domvm.defineElement;
const cv = domvm.createView;

const motherTpl = require(./motherTpl)

function MainView() {
    return function(vm, data) {
        return el('#main', [
            motherTpl()
        ]);
    }
}

var data = {
    user: {
        name: "Leon",
    }
};

cv(MainView, data).mount(document.body);
```

```javascript
// motherTpl.js
const el = domvm.defineElement;
const childTpl = require(./childTpl)

function motherTpl() {
    return el('#mother', [
        childTpl()
    ]);
}

module.exports = motherTpl;
```

```javascript
// childTpl.js
const el = domvm.defineElement;

function childTpl() {
    return el('#child', data.user.name);
}

module.exports = childTpl;
```

Then, in this `childTpl`, we'd like to access the data from `main.js`. But, the `childTpl` function has no reference to its parent `VNode`. `motherTpl`'s `VNode` doesn't even exist, yet. So it seems, in this scenario, your only option is prop-drilling the `vm` or `data` through each function?

I was thinking maybe I could do something with `defineElement`, possibly bind the data to the template functions. Unfortunately, due to the order of execution, I don't think what I was attempting would work. E.g. if we put a `console.log(tag)` inside `domvm.defineElement`, we clearly see the execution order as `#child`, `#mother`, `#main`.


@lawrence-dol, so is what you're outlining similar to the code I've pasted above? Or is more like this:

```javascript
// childTpl.js
const el = domvm.defineElement;

function childTpl() {
    return el('#child', 'Some data');
}

module.exports = function(args) {
    return {
        render : function() {
            return childTpl();
        }
    }
}
```

**Comment by lawrence-dol** [comment]
@Veid : I tend to keep my state pretty coarse, in separate "model" objects. These objects consist of a collection of values exposed as property getter/setter (PGS) functions which have each been wired up to trigger a redraw (coalesced and deferred to the event loop) when their value changes. The coalescing means that even if a hundred properties change in an event, only one redraw is done.    

With subtemplate modules I just inject the needed state objects into the constructor, and because each property is it's own PGS the principle model objects live for the life of the app, and and their values mutate, triggering redraws automatically as they do. With subviews (true components), which are surprisingly rare outside of library code, the needed models are injected in via the data argument, and a reference stored in the object enclosure. In both cases the other functions in the module have access to the models directly without having to drill them down into every function.

But therein lies my secret. For each subview/subtemplate I have the constructor function closure, which returns an object of it's imports, and therefore I have a complete module body of code which is self-contained and does not use `this` at all. Anywhere. This is using closure-based modules, which works because I don't create views for every single little UI concept -- rather I use subtemplates for most of them, and views only for the major UI components. Hopefully, this is clearer than mud, but to help a little bit I'll end it here with a template of a "module" as I create them (ala Doug Crockford way back in the day), and the slightly altered form which I use for a DOMVM View.

````
let SomeUiModule=function(rootNode,appConfig,mdlThisSuff,mdlOtherStuff)
{
"use strict";                                                                                                           // must encapsulate in one function for strict to apply to all code
let exported=this||{};

const xxx                               = "some value"
,     yyy                               = "another value"
,     ...

let   zzz
,     aaa
,     ...

// *********************************************************************************************************************
// CONSTRUCTION
// *********************************************************************************************************************

function init() {                                                                                                       // self-contained initialization avoids leaking temp objects into module closure
    }

// *********************************************************************************************************************
// MODULE FUNCTIONS - PUBLIC API
// *********************************************************************************************************************

exported.thisIsPublic=thisIsPublic;
function thisIsPublic() {
    // this can be invoked internally using thisIsPublicToo().
    }

exported.thisIsPublicToo=
function thisIsPublicToo() {
    // this must be invoked internally using exported.thisIsPublicToo().
    }

// *********************************************************************************************************************
// MODULE FUNCTIONS - PRIVATE
// *********************************************************************************************************************

function thisIsPrivate() {
    }

// *********************************************************************************************************************
init();
return Object.freeze(exported);                                                                                         // allow invocation with or without new
};
````

````
let CptAutocomplete=function()
{
"use strict";                                                                                                           // must encapsulate in one function for strict to apply to all code
let exported=this||{};

let   cptVm                             = null
,     cptProps                          = null
,     mdlThisSuff                       = null
,     mdlOtherStuff                     = null

// *********************************************************************************************************************
// CONSTRUCTION
// *********************************************************************************************************************

exported.init=init;
function init(vm) {                                                                                                     // invoked by DOM after construction
    cptVm=vm;
    cptProps={};
    }

function updateProps(newprps) {
    cptProps=newprps;
    mdlThisSuff=cptProp.mdlThisSuff;
    mdlOtherStuff=cptProps.mdlOtherStuff;
    }

// *********************************************************************************************************************
// HOOKS
// *********************************************************************************************************************

// *********************************************************************************************************************
// VIEWS
// *********************************************************************************************************************

exported.render=render;
function render(vm,curprp) {
    updateProps(curprp);
    return el("",{},[
        ...
        ]);
    }

function updateUI() {
    genU.deferCoalescedEL(() => {
        if(cptVm && cptVm.render) { cptVm.redraw(); }
        });
    }

// *********************************************************************************************************************
// EVENT HANDLERS
// *********************************************************************************************************************



// *********************************************************************************************************************
// PRIVATE UTILITY
// *********************************************************************************************************************



// *********************************************************************************************************************
// init() will be called by the vDOM library
// Don't freeze -- components belong to DOMVM
return exported;
};
````

**Comment by lawrence-dol** [comment]
@Veid : Is there anything more we can help you with on this issue?

**Comment by lawrence-dol** [comment]
@leeoniya : I suggest closing this issue.

**Comment by lawrence-dol** [comment]
Closing -- approaching 3 years old.
