### ISSUE TITLE
DOMVM vs. React... FTW

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#214]
This is not an issue, but I wanted to publicly thank Leon for the sterling job in creating and refining DOMVM to be the perfect little vDOM library. Neither doing too little, nor too much.

Over the last week I took a risk, against management preference, to rewrite an app written with React that was proving difficult to modify, both brittle and confusing (using React's class-based API). I jumped into it last weekend, on my own time to see how far I could get, and was pleasantly surprised to find the essential functionality and the entire user interface done and dusted by Sun afternoon. The rest, including integration of third party code and some overlooked stuff took until Thu, and I spent today refactoring and refining. In the process I wrote a lot of code, mostly app code, but also two generic components.

What really struck me though was just how well DOMVM does what it does, and gets out of your way for the rest of it. The idioms available for refactoring common code as it arose, removing duplication and employing functional concepts to produce really nice abstractions really came out with a focus on doing things the way that Javascript is really good at, rather than the way that the framework-that-shall-not-be-named forces you to do it (or, at least, impels you toward). It's hard to understand the difference until you've worked extensively with the two approaches back-to-back like I have over the last three weeks. It's the difference between a library, doing one job and doing it well, and a framework which tries to make too many decisions for you.

Anyway, suffice it to say, that once again DOMVM has brought much joy to my front-end development, and for this I am very grateful. Thanks Leon!

**Comment by leeoniya** [comment]
thanks for the kind words!

as always, i'd be interested to hear the LOC, app size & perf differences (both load time and interaction latency) between the two versions.

>  I jumped into it last weekend, on my own time to see how far I could get, and was pleasantly surprised

since it turned out well, i hope you got to recoup that dev time :D

> What really struck me though was just how well DOMVM does what it does, and gets out of your way for the rest of it.

most frameworks keep growing because devs get paid to add features to them and clients pay to have frameworks will all the bells and whistles. any restriction on focus creep in such an environment is impossible by design. domvm was not meant to support 10k devs at FB with huge infrastructure, CI farms and 3B active users - and it would suck badly at it. nor was it meant to be a 1,000 year lib - like jQuery, it will continue to do its limited job forever and if at some that job becomes irrelevant, then it will fade into obscurity like 99.999% of code ever written. i can easily tell domvm's non-paying users that if it doesn't meet their requirements, they're welcome to evaluate any of 1e6 other more popular options. can you ever imagine having that convo with a potential client?!

that being said, my company is soon launching a bottom-up rewrite of our e-commerce site (thousands of products) in domvm with full SSR. on a cheap $40/mo Linode instance it can handle hundreds of simultaneous visitors (but in reality ~10k pageviews/day) without breaking a sweat, and probably an order of magnitude more. the entire site builds in < 30s (including static html fallbacks if Node or MySQL take a shit, or we get hit with DoS or a bad scraper). without exaggeration, the staging server is currently the fastest e-commerce site that i've been able to find. it's so fast, in fact, that we'd have serious UX issues if the browser didn't need to load different banners & product images on each page (since there's only about a dozen top-level templates). i may write a blogpost about the whole experience later.

i'm glad at least one other person has found domvm to be an acceptable experience, and thanks for all the feedback you've given me with polishing it :)

i guess i won't waste this opportunity to plug my latest project: https://github.com/leeoniya/uPlot, and in case you missed it, my previous one: https://github.com/leeoniya/dropcss

cheers!

**Comment by lawrence-dol** [comment]
It's not a huge app, so performance differences in load time were unnoticeable until I throttled to 2G mobile speeds where the new APP was OK and React was a little painful. Total (minimized/wire) app size was reduced from 374K/112K to 109K/32K (but a lot of that is library code). Actual app LOC size was reduced from 3425 to 1803.

There was no visible difference in interaction latency, as none of the view were even remotely large enough for that to matter.
