### ISSUE TITLE
Getting the VM of a child.

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#218]
When a component is used via `defineView` DOMVM creates the component and it's related VM on demand. How should the parent obtain the VM for the current component in the event that it was to trigger targeted redraws?

Currently I am changing it's props and redrawing the app, but sometimes it would be better to directly update it's props and make only the subview redraw.

**Comment by leeoniya** [comment]
search downwards recursively from `vm.vnode.body`. see [1].

`vm.body()` [2] is a helper available in micro+ builds that does a portion of this, but it just does a variant of the above. feel free to extend the ViewModel prototype with something like `vm.findDown(condition) -> subVm`.

just don't keep references to the subVm in the ancestor vm unless it's some permanent UI fixture, otherwise you'll leak mem since the subVm won't be GC'd when removed but ancestor remains.

[1] https://github.com/domvm/domvm#parents--roots
[2] https://github.com/domvm/domvm/blob/master/src/view/addons/vmBody.js

**Comment by leeoniya** [comment]
we had this discussion before, remember? :)

https://github.com/domvm/domvm/issues/17
https://github.com/domvm/domvm/pull/19

**Comment by lawrence-dol** [comment]
> we had this discussion before, remember? :)

That was 3 years ago, sometimes I can hardly remember last week! :-D

Thanks, Leon.
