### ISSUE TITLE
Access context outside of render function

### ISSUE THREAD

**Issue by vdenisenko-waverley** [domvm/domvm#220]
I'm using [context example](https://domvm.github.io/domvm/demos/playground/#context) to drill down app state, which works very well. Now I'm wondering if there is a way to access prop outside of render function?

```
function UserInfo(vm) {
        // ??? access "user" here ???

	return (vm, data, key, newPar) => {
		return el("strong", newPar.pull("user").name);
	}
}
```

**Comment by lawrence-dol** [comment]
The initial values of props is also passed as the second argument to UserInfo: `function UserInfo(vm,iniprp)`.

**Comment by vdenisenko-waverley** [comment]
> The initial values of props is also passed as the second argument to UserInfo: `function UserInfo(vm,iniprp)`.

If I try to access it inside linked example - it is not available, for example:
```
function UserInfo(vm, initprops) {
        console.log(initprops); // >>> undefined

	return (vm, data, key, newPar) => {
		return el("strong", newPar.pull("user").name);
	}
}
```

This is expected because `initprops` contains initial props passed to view explicitly, but is there a way to access context props, in our case its some kind of `newPar.pull("user").name`?

**Comment by lawrence-dol** [comment]
It's difficult to answer well without more context -- how do your want to create it, and what do you want to do with props? If you don't pass initial props, then no props will be available until the first render.

Possiblly you might want to use the object return form:

````
function UserInfo(vm) {
    return { init,render };

    function init(vm,iniprp) {
        console.log(iniprp);
        },
    function render(vm,newprp) {
        return el("div", "Hello World!");
        },
    };
````

**Comment by leeoniya** [comment]
it might be possible to also pass `newPar` to the ViewModal constructor so you can do `newPar.pull("user").name` outside of `render()`.

if you put a breakpoint on "init B" in the following code:

```js
function A(vm) {
    console.log("init A");

    return () => el("#foo", [
        vw(B)
    ]);
}

function B(vm) {
    console.log("init B");

    return () =>
        el("#bar", "Hello World!");
}

cv(A).mount(document.body);
```

...and walk up the callstack, you'll see that we just need to pass `vnode` as an additional argument to `createView`:

https://github.com/domvm/domvm/blob/8e0ef3c8a7fae78e3c4a9342b3d8d38c03c0f2a9/src/view/hydrate.js#L18

my concern with this would be memory leaks, since you're now holding a permanent reference to the parent `vnode` in the constructor closure.

it may not be an issue if you never actually use `newPar` in the constructor and the JS engine will recognize that and be able to release it when that vnode goes stale after some ancestor is redrawn. it's possible that this is the way to avoid leaks:

```js
function B(vm, data, key, opts, parentVnode) {
    console.log("init B");
    
    let someThing = parentVnode.pull("someThing");

    return (vm, data, key, newPar) => {
        parentVnode = newPar;
        return el("#bar", "Hello World!");
    }
}
```

or maybe the JS engine will see that `parentVnode` is never used after the initial view constructor and will avoid leaks by releasing it immediately. i don't know for sure, but it might be worth testing.

all that being said, if you do not need `someThing` at the time of view init, what i do is simply refresh it on each render:

```js
function B(vm, data, key, opts) {
    console.log("init B");
    
    let someThing;
    
    function useSomething() {
		alert(someThing);
    }

    return (vm, data, key, newPar) => {
        someThing = newPar.pull("someThing");
        return el("#bar", {onclick: useSomething}, "Hello World!");
    }
}
```

**Comment by lawrence-dol** [comment]
@vdenisenko-waverley : How did you fare with this? Is there any way we can help you further on this issue?

**Comment by lawrence-dol** [comment]
@leeoniya : I suggest closing this issue.
