### ISSUE TITLE
navigator is not defined 

### ISSUE THREAD

**Issue by lesar** [domvm/domvm#222]
I'm try to make a isomorphic web app running on node server. I use:
```javascript
import { createView as cv } from 'domvm/dist/full/domvm.full.es'
// .......
    const content = cv(App, { states, update, actions, viewsMap, componentsMap, ssr: true }).html()
// ...........
```
where content have to be my html text string  
All compile well but starting I get:  
> navigator is not defined 

it is executed on first row of domvm function:  
`function DOMInstr`  

I'm try to do ssr by get `vm.html()` and I think on node server window and his child object are not defined, so why domvm is execute DOMInstr function?  

Have I do some mistake?  

best regards,  
Leonardo

**Comment by lawrence-dol** [comment]
Do you have DEVMODE settings active. I did a quick search on the code and navigator is only used if `DEVMODE.mutations` is set `true`.

**Comment by lesar** [comment]
Yes, how suggest by documentation I import the dev package by alias in rollup config.  
Tomorrow I disable the alias and than I let you know.  
Thank you.
Best regards,
Leonardo

**Comment by lesar** [comment]
I switch out from DEVMODE and after some debug all go well thank you very much.  
I like domvm very much.  
  
You suggest to stay in DEVMODE and turn off DEVMODE.mutations to make first test using domvm? (I'm new to it)  

Debugging I have some problem on watch mode: if I start the application and then modify a file rollup recompile all but if I do a refresh on web page no change are show.  
I have to stop the ap, rebuild and restart to see the change.  
I have put this at the beginning:  
```javascript
isDev && cfg({
  syncRedraw: true
})
```
but no change are show.  

have any suggest?

best regards,
Leonardo

P.S. if better I can put this new question on new post. let me know

**Comment by lawrence-dol** [comment]
> You suggest to stay in DEVMODE and turn off DEVMODE.mutations to make first test using domvm? (I'm new to it)

Personally, I rarely use the dev package, but for a developer new to DOMVM it will be helpful to develop with it, in your case with `mutations=false`.

> ... if I start the application and then modify a file rollup recompile all but if I do a refresh on web page no change are show. I have to stop the ap, rebuild and restart to see the change.

This almost certainly has nothing to do with DOMVM; it sounds like a caching issue. Since you mentioned having as isomorphic app and "starting" and "stopping" the app, I suspect your problem is that your host is not hot-reloading the code. That's where I would look.

> but no change are show.

You haven't provided much context for when you expect a change to be shown, and this seems unrelated to the stop/start issue (paragraphs would help), so I'm guessing here.

`syncRedraw` is used to perform all redraws inline with the call instead of deferring to the next animation frame. It really only relates to the timeliness of repainting. In all my apps, which don't require animation-like refresh, I actually defer all UI updates to the event loop and I've never had a problem with timeliness of update.

The general approach is that on each render you regenerate the _entire_ vDOM for a given view-model from the current state of the app, and the DOM is _entirely_ updated by DOMVM. You should have no state held in DOM; input states, content, etc, are immediately store in your view-model (via change hooks). The mental model you must have is that at any moment the entire DOM could be completely discarded and then be perfectly correctly recreated from your application state alone.

I hope this helps you out. Feel free to elaborate further if I've guessed wrongly.

**Comment by leeoniya** [comment]
@lawrence-dol thanks for jumping in to help here, i'm a bit busy with https://github.com/leeoniya/uPlot these days. i have a small local prototype that uses domvm and uPlot to make a super lightweight, grafana-like monitoring dashboard. maybe when i get it to a more demo-able state, i'll publish it ;)

**Comment by lesar** [comment]
Thanks a lot @lawrence-dol and @leeoniya  for your interest.  
@lawrence-do help me to start my new app using domvm  
the app is working  
and I'm hunting the caching problem.

bets regards,
Leonardo
