### ISSUE TITLE
DOMVM Library - Deploy Bundled or As a Shared Dependency?

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#225]
I usually bundle my entire app or component as a blackboxed function which includes a copy of DOMVM nano. This is great for apps, and OK for large components, but for smaller components (as I build out a library) it would be a significant overhead to duplicate DOMVM for each one. For this library, should I list DOMVM as a dependency instead of bundling it?

What is the relationship, if any, between separately mounted DOMVM views? That is, if DOMVM is loaded once by the page and used by multiple different, disparate components to mount separate views (some even mounted as foreign subtrees within other DOMVM views), is there any problem likely to surface because the same DOMVM is shared in this manner?

What about global options? Are there any options which could break the operation of views by changing them?

**Comment by leeoniya** [comment]
i very much recommend using it as a shared library rather than having copies. i think it's much better for the JIT to hit the same function 1,000 times instead of 10 copies of the same function 100 time each. off the top of my head i dont think there is any kind of sharing that would preclude it from being used the same way across a whole app. and in fact, this is how https://us.thermosoft.com/ is built.

> some even mounted as foreign subtrees within other DOMVM views

as long as the same view _instances_ (created via createView) are not mounted in different sub-trees at the same time (via injectView), it should be just fine.

try it and let me know!
