### ISSUE TITLE
Bug in SVG Code?

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#228]
I was curious as to how SVG was supported and how it differed from "normal" elements. I found the following code, which seems to be faulty.

````
// if body-less svg node, auto-close & return
if (node.body == null && node.ns != null && node.tag !== "svg")
	return buf + "/>";
else
	buf += ">";
````

If the comment is correct, and it seems to be, the condition should be inverted:

````
if (node.body == null && node.ns != null && node.tag === "svg")
````

But it seems like it's possible that it might be intended to autoclose for any tag where the namespace is set (which would identify it as an XML tag instead of HTML); I'm thinking of MathML, for example. In which case the tag test should be removed altogether.

**Comment by leeoniya** [comment]
sorry, didn't see this till now.

i think the intention here was to auto-close opening tags of all svg descendant nodes (created via `defineSvg()` and having non-null `node.ns`), but _not_ auto-close the `<svg>` root element itself.

i can't remember why the root element was specifically excluded from auto-closing, since it will pretty much always contain a body, and when it doesnt, auto-closing it should have no effect. maybe for some reason it was to avoid something like `<svg/></svg>` since there is no explicit list of void svg elements in domvm, like there is for HTML.
